# Generated by Django 5.0.2 on 2025-04-23 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profile",
            options={"verbose_name": "پرفایل", "verbose_name_plural": "پروفایل ها"},
        ),
    ]
