# Generated by Django 5.0.2 on 2025-02-18 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_alter_post_options_comment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="body",
        ),
    ]
