# Generated by Django 5.0.2 on 2025-02-26 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_remove_comment_body"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="comment",
            new_name="comment1",
        ),
    ]
