# Generated by Django 5.0.2 on 2025-02-27 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0008_rename_comment1_comment_comment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="article",
            new_name="post",
        ),
    ]
