# Generated by Django 5.0.2 on 2025-02-27 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0010_rename_post_comment_article"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="article",
            new_name="post",
        ),
    ]
