# Generated by Django 5.0.2 on 2025-04-23 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0012_message"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "نمونه", "verbose_name_plural": "نمونه ها"},
        ),
        migrations.AlterModelOptions(
            name="comment",
            options={"verbose_name": "کامنت ها", "verbose_name_plural": "کامنت"},
        ),
        migrations.AlterModelOptions(
            name="message",
            options={"verbose_name": "پیام", "verbose_name_plural": "پیام ها"},
        ),
        migrations.AlterModelOptions(
            name="post",
            options={
                "ordering": ["-created"],
                "verbose_name": "مقاله",
                "verbose_name_plural": "مقاله ها",
            },
        ),
        migrations.CreateModel(
            name="Like",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to="blog.post",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
